services:
  pod:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - runpod-comfyui:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports: 
      - "8188:8188"  # ComfyUI web interface
      - "8888:8888"  # JupyterLab
      - "8675:8675"  # AI Toolkit
      - "8000:8001"  # Additional service
    volumes:
      - output:/comfyui/output
      - models:/comfyui/models
      - workspace:/workspace
      # Uncomment and adjust path as needed:
      # - /Volumes/HD\ 2TB/2\ -\ REICA/models:/comfyui/models/
    environment:
      - SERVE_API_LOCALLY=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  output:
    driver: local
  models:
    driver: local  
  workspace:
    driver: local